on:
  workflow_dispatch:
    inputs:
      vscode_version:
        description: VSCode version tag
        default: ""
        required: false

name: Build

jobs:
  bulid:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout vscode
        run: |
          git -C vscode/ fetch --depth=1 origin refs/tags/${{ github.event.inputs.vscode_version }}:refs/tags/${{ github.event.inputs.vscode_version }} --no-tags
          git -C vscode/ checkout FETCH_HEAD
        if: ${{ github.event.inputs.vscode_version != '' }}
      - name: Set vscode commit
        id: vscode-commit
        run: echo "VSCODE_SHA=$(git -C vscode/ rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Cache vscode
        uses: actions/cache@v3
        env:
          cache-name: cache-vscode
        with:
          path: |
            vscode/
          key: ${{ env.cache-name }}-build-${{ steps.vscode-commit.outputs.VSCODE_SHA }}
          restore-keys: ${{ env.cache-name }}-bulid-
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=20.x'
      - name: Install toolchains
        run: |
          sudo apt-get update -y \
          && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl git zip build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 \
          && sudo apt-get -y clean \
          && sudo rm -rf /var/lib/apt/lists/* \
          && echo "node $(node --version)" \
          && echo "yarn $(yarn --version)"
      - name: Build vscode-web-min
        run: BUILD_ROOT=$GITHUB_WORKSPACE bash ./build.sh
      - name: Set relesae tag
        id: release-tag
        run: echo "RELEASE_TAG=$(echo '${{ github.event.inputs.vscode_version }}' | sed -e 's/^\(refs\/\)\?tags\///g')" >> $GITHUB_OUTPUT
        if: startsWith(${{ github.event.inputs.vscode_version }}, 'tags/')
      - name: Release vscode-web-min
        uses: softprops/action-gh-release@v1
        if: startsWith(${{ github.event.inputs.vscode_version }}, 'tags/')
        with:
          name: ${{ steps.release-tag.outputs.RELEASE_TAG }}
          tag_name: ${{ steps.release-tag.outputs.RELEASE_TAG }}
          files: out/*.zip
          fail_on_unmatched_files: true

